### ISSUE TITLE
small library for std::ios

### ISSUE THREAD

**Issue by gpeterhoff** [boostorg/utility#104]
Hello,
I have developed a small library for accessing std::ios. This saves manual handling of e.g. ios::flags etc.
Could you please include this in boost?
Is boost/utility the right location?

[ios.hpp.txt](https://github.com/boostorg/utility/files/11338238/ios.hpp.txt)

thx
Gero

**Comment by Lastique** [comment]
There is already Boost.IO, in particular [`io_state.hpp`](https://github.com/boostorg/io/blob/83e927f998e83a29be8fb033389110affe8787f5/include/boost/io/ios_state.hpp).

Also, for future reference, code submissions should follow [Boost coding guidelines](https://www.boost.org/development/requirements.html#Design_and_Programming), in particular, don't use tabs. Submissions should include documentation and tests. Among other things, docs should include motivation.
