### ISSUE TITLE
Break dependence on MPL

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/utility#32]
Utility depends on MPL just for result_of.hpp. It would be nice if we could break this dependency, as it is circular.

**Comment by pdimov** [comment]
Right.

https://github.com/boostorg/utility/commit/7d101d420c01a2a17dc1ebe8d10d0cbea50a7508
https://github.com/boostorg/utility/commit/9d46de15782ee039aa82b37e6dff6c5cdbe6e67a
