### ISSUE TITLE
Define boost::hash (and maybe std::hash) for string_view

### ISSUE THREAD

**Issue by dimztimz** [boostorg/utility#44]
This is a feature request.

The requirement that it should return the same hash for equal `std::string` should be met.

Additionally, if possible, provide `std::hash<string_view>` with the above requirement, although this is probably not possible to do efficiently because there is no thing like `std::hash(char* ptr, size_t len)`.

**Comment by mclow** [comment]
We can do something like this for `boost::hash` (make `string/string_view` return the same value), but making that work for `std::hash` is not possible (since the standard library provides the hash for `string`) w/o creating a temporary string, and I don't think we want to do that.

**Comment by dimztimz** [comment]
`boost::hash<string_view>` and `hash_value(string_view)` should be provided in the same header as string_view, `string_view.hpp`. This is how `std hash` is defined for string, it's in the same header as string, you don't include `<string_hash>`.

Otherwise, it will just confuse the users.

**Comment by Lastique** [comment]
There's nothing confusing about having integration stuff in separate headers. This is common practice in Boost. Although, I have to admit, supporting Boost.Hash is cheap - it doesn't require including its headers, you just have to define `hash_value` function overload. So maybe it's not worth the hassle to have it in a separate header.

`std::hash` is different, it requires you to include the whole `<functional>` just to get the forward declaration of the `std::hash` template.
