### ISSUE TITLE
Non-standard license header in utility/detail/minstd_rand.hpp

### ISSUE THREAD

**Issue by rdoeffinger** [boostorg/utility#48]
@pdimov Could you please consider copy-pasting one of the standard format license headers from e.g. boost/algorithm/cxx17/reduce.hpp (they also refer to the name of the license file for example).
This makes it easier to do compliance scanning, which is of particular concern for boost due to the proliferation of boostinspect:nolicense files (and files with no copyright information at all).
Would be much appreciated!

**Comment by pdimov** [comment]
The "standard" license header in `boost/algorithm/cxx17/reduce.hpp` refers to the nonexistent file `http://www.boost.org/LICENSE10.txt` but point taken.

**Comment by mclow** [comment]
Fixed the broken links in Boost.Algorithm (8x). Thanks for the heads-up!

**Comment by pdimov** [comment]
There we go: https://github.com/boostorg/utility/commit/bdf55e0b6f52f5d4bf40c381fbb8ae7060510c15

Should I cherry-pick this into master for the upcoming release, @mclow?

**Comment by mclow** [comment]
I'm being paranoid and will merge my changes in Boost.Algorithm Wednesday morning (after the bots cycle).  But you can go ahead.
