### ISSUE TITLE
Why compressed_pair use call_traits?

### ISSUE THREAD

**Issue by FirstLoveLife** [boostorg/utility#53]
I cannot see any pros of using call_traits [here](https://github.com/boostorg/utility/blob/master/include/boost/detail/compressed_pair.hpp#L110). They just provide alias here, trival typedef/using is enough, imo.

**Comment by Lastique** [comment]
If you look at `boost::call_traits` implementation, `param_type` definition is not quite trivial. It provides a more efficient way to pass small arguments to constructors of `compressed_pair`. I don't see a compelling reason to replicate that logic in Boost.CompressedPair.
