### ISSUE TITLE
Boost.Operators should embrace constexpr

### ISSUE THREAD

**Issue by tonyelewis** [boostorg/utility#54]
Thanks to the maintainers of Boost.Utility.

IMHO, the biggest limitation of Boost.Operators is that the operators it provides aren't `constexpr`. My initial experiments seem to suggest that adding `BOOST_CONSTEXPR` / `BOOST_CXX14_CONSTEXPR` to `operators.hpp` does the trick.

 Would a PR along these lines be welcome? Any non-obvious issues of which I should be aware?

**Comment by tonyelewis** [comment]
(this follows on from [Trac#9044](https://svn.boost.org/trac10/ticket/9044))

**Comment by d-frey** [comment]
A PR would be welcome for the comparison operators.

**Comment by tonyelewis** [comment]
Thanks very much. I'm happy for this issue to be closed.

**Comment by d-frey** [comment]
Thank you for contributing and sorry that it took me so long. Stay safe and happy hacking! 🍀

**Comment by tonyelewis** [comment]
:slightly_smiling_face: You too.
