### ISSUE TITLE
Avoid using "<=>"

### ISSUE THREAD

**Issue by Little-Flower-171** [boostorg/utility#59]
<https://www.boost.org/doc/libs/1_70_0/libs/utility/operators.htm#rationale> says:

> [...] Moreover, unless your class has really surprising behavior, some of these related operators can be defined in terms of others (e.g. `x >= y <=> !(x < y)`). [...]

Since `<=>` becomes a single token in C++20 (the [three-way comparison operator](https://en.cppreference.com/w/cpp/language/operator_comparison#Three-way_comparison)), I would suggest rephrasing to prevent possible confusion. Like this:

> [...] Moreover, unless your class has really surprising behavior, some of these related operators can be defined in terms of others (e.g. `x >= y` is equivalent to `!(x < y)`). [...]

That's better, isn't it?

**Comment by d-frey** [comment]
Indeed, thanks for the suggestion.
