### ISSUE TITLE
add c++20/23 constructors to basic_string_view

### ISSUE THREAD

**Issue by sehe** [boostorg/utility#95]
The following constructors were added:

```c++
template <class It, class End> constexpr basic_string_view(It first, End last);
template <class R> constexpr basic_string_view(R&& r);
constexpr basic_string_view(std::nullptr_t) = delete;
```

(where `It`/`End` and `R` are subject to the usual restrictions)

People might expect these to be present on the Boost implementation.

**Comment by Lastique** [comment]
Given the feedback in https://github.com/boostorg/core/issues/113, I kind of agree that the second constructor is probably a bad idea. The first one requires a modern standard library as it must only compile for contiguous iterators, which is C++20 I think. We currently don't have the infrastructure for this. I don't find the third one very useful, but fine, I guess.

**Comment by sehe** [comment]
I agree on the third one.

Let's accept this as not desirable for now. In reality, the purpose of string_view alternatives outside the standard library are either supporting older compilers (so the missing c++20+ constructors are moot) or adding interoperability benefits (e.g. `core::string_view`).
